#30/04/2021   Ivan Martin Hernandez
#Script that analize the JSON with th data of the AB PDB generated by the perl script "AB_SAbDab_sumarize.pl"


#Libraries
library(ggplot2)
library(ggrepel)
library(ggpubr)
theme_set(theme_pubr())
library(dplyr)
#Use the library rjson to read the JSON file.
library(rjson)


#################
# Funciones
#################

mode <- function(x) {
  return(as.numeric(names(which.max(table(x)))))
}



# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)
  
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots==1) {
    print(plots[[1]])
    
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}











#Improt the data from JSON into a complex list
data <- fromJSON(file = "AB_loop.json")

pdbs=vector()
have_antigen=vector()
N_antigenenicunits=vector()
resolution=vector()
r_factor=vector()
AB_type=vector()
Method=vector()
Have_H=vector()
Have_L=vector()
Especie=vector()

print(length(data))

for (i in 1:length(data)){
  pdbs = c(pdbs,data[[i]]$PDB)
  have_antigen = c(have_antigen,data[[i]]$`Have antigen`)
  N_antigenenicunits = c(N_antigenenicunits,data[[i]]$`Nº ABs`)
  resolution = c(resolution,data[[i]]$Resolution)
  r_factor = c(r_factor,data[[i]]$r_factor)
  AB_type = c(AB_type,data[[i]]$`AB type`)
  Method = c(Method,data[[i]]$Method)
  Especie= c(Especie,data[[i]]$Organism)

}




#Generation of a matrix with the data of each structure for the creation of ggplots


matriz <- cbind( have_antigen,N_antigenenicunits,resolution,AB_type,Method,Especie)
dataframe=as.data.frame(matriz,row.names = pdbs)

  #opcion b
dataframe2 <- tibble(pdbs,have_antigen,N_antigenenicunits,resolution,AB_type,Method)



############# GGplots ##########################

# Pie chart --> Species

dfe <- dataframe %>%
  group_by(Especie) %>%
  summarise(counts = n())
dfe <- dfe %>%
  arrange(desc(counts)) 

va<-sum(dfe$counts)
vb<-sum(dfe2$counts)
diffvalue <- va -vb

dfe2 <- head(dfe,7)
others <- data.frame("Otras",diffvalue )
names(others)<-c("Especie", "counts")
dfe2<-rbind(dfe2,others)

dfe <- dfe %>%
  arrange(desc(counts)) %>%
  mutate(prop = round(counts*100/sum(counts), 1),
         lab.ypos = cumsum(prop) - 0.5*prop)

dfe2 <- dfe2 %>%
  arrange(desc(Especie)) %>%
  mutate(prop = round(counts*100/sum(counts), 1),
         lab.ypos = cumsum(prop) - 0.5*prop)




sp <- ggplot(dfe2, aes(x = "", y = prop, fill = Especie)) +
  labs(fill="Especie") +
  geom_bar(width = 1, stat = "identity", color = "white") +
  geom_text(aes(y = lab.ypos, label = counts), color = "white")+
  coord_polar("y", start = 0)+
  ggpubr::fill_palette("jco")+
  theme_void()+
  theme(legend.title = element_text(size = 15),legend.position="top")
print(sp)


sp <- ggplot(dfe2, aes(x = "", y = prop, fill = Especie)) +
  labs(fill="Especie") +
  geom_bar(width = 1, stat = "identity", color = "black") +
  geom_label_repel(data = dfe2,
                   aes(y = lab.ypos, label = counts),
                   size = 4.5, nudge_x = 1, show.legend = FALSE) +
  coord_polar("y", start = 0)+
  scale_fill_brewer(palette = "Pastel1") +
  theme_void()+
  theme(legend.title = element_text(size = 15),legend.position="top")
print(sp)




# Pie chart --> Have Antigen
df <- dataframe %>%
  group_by(have_antigen) %>%
  summarise(counts = n())

df <- df %>%
  arrange(desc(have_antigen)) %>%
  mutate(prop = round(counts*100/sum(counts), 1),
         lab.ypos = cumsum(prop) - 0.5*prop)



a <- ggplot(df, aes(x = "", y = prop, fill = have_antigen)) +
  labs(fill="Antigen present in the PDB") +
  geom_bar(width = 1, stat = "identity", color = "white") +
  geom_text(aes(y = lab.ypos, label = counts), color = "white")+
  coord_polar("y", start = 0)+
  ggpubr::fill_palette("jco")+
  theme_void()+
  theme(legend.title = element_text(size = 15),legend.position="top")
print(a)


a <- ggplot(df, aes(x = "", y = prop, fill = have_antigen)) +
  labs(fill="Antigeno presente en el PDB") +
  geom_bar(width = 1, stat = "identity", color = "black") +
  geom_label_repel(data = df,
                   aes(y = lab.ypos, label = counts),
                   size = 4.5, nudge_x = 1, show.legend = FALSE) +  coord_polar("y", start = 0)+
  ggpubr::fill_palette("jco")+
  theme_void()+
  theme(legend.title = element_text(size = 15),legend.position="top")
print(a)




# Bar chart Number of antigen per PDB

dataframeNant<-dataframe
dataframeNant$N_antigenenicunits<- as.numeric(as.character((dataframeNant$N_antigenenicunits)))
dataframeNant$N_antigenenicunits[dataframeNant$N_antigenenicunits >=10] <- 10

dataframeNant$N_antigenenicunits<- as.factor(dataframeNant$N_antigenenicunits)


df2 <- dataframeNant %>%
   group_by(N_antigenenicunits) %>%
  summarise(counts = n())


sorted_labels <- sort(as.integer(levels(dataframeNant$N_antigenenicunits)))


sorted_labels
df2$N_antigenenicunits <- factor(df2$N_antigenenicunits, levels = sorted_labels)

b<-ggplot(df2, aes(x = N_antigenenicunits, y = counts)) +
  labs(title="Numero de unidades antigenicas por PDB")+
  xlab("Numero de unidades antigenicas")+ ylab("Ocurrencias")+
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = counts), vjust = -0.3) + 
  theme_pubclean()+
  theme(plot.title = element_text(hjust=0.5,size =18))

print(b)


# Pie chart --> Type of Antibody
df3 <- dataframe %>%
  group_by(AB_type) %>%
  summarise(counts = n())

df3 <- df3 %>%
  arrange(desc(AB_type)) %>%
  mutate(prop = round(counts*100/sum(counts), 1),
         lab.ypos = cumsum(prop) - 0.5*prop)




c <- ggplot(df3, aes(x = "", y = prop, fill = AB_type)) +
  labs(fill="Tipo de anticuerpo") +
  geom_bar(width = 1, stat = "identity", color = "black") +
  geom_label_repel(data = df3,
                   aes(y = lab.ypos, label = counts),
                   size = 4.5, nudge_x = 1, show.legend = FALSE) +  coord_polar("y", start = 0)+  coord_polar("y", start = 0)+
  ggpubr::fill_palette("gsea")+
  theme_void()+
  theme(legend.title = element_text(size = 15),legend.position="top")
print(c)


c <- ggplot(df3, aes(x = "", y = prop, fill = AB_type)) +
  labs(fill="Tipo de anticuerpo") +
  geom_bar(width = 1, stat = "identity", color = "white") +
  geom_text(aes(y = lab.ypos, label = counts), color = "white")+
  coord_polar("y", start = 0)+
  ggpubr::fill_palette("gsea")+
  theme_void()+
  theme(legend.title = element_text(size = 15),legend.position="top")
print(c)




# Histogram chart Resolution
 
df4 = subset(dataframe2, resolution<8 )





d <- ggplot(df4, aes(x = resolution)) +
  labs(title="Distribucion de resolución")+
  xlab("Resolución (Å)")+ ylab("Densidad")+
  geom_density(fill = "#FC4E07", alpha=0.4)+
  geom_vline(aes(xintercept = mean(resolution)), linetype = "dashed",  size = 0.6, color = "#3C0B15")+
  geom_text(aes(x=mean(resolution)+1, label=paste0("Mean:\n",round(mean(resolution),2)," Å" ), y=0.41))+
  theme_pubclean()+ 
  theme(plot.title = element_text(hjust=0.5,size =18))

print(d)






# Pie chart --> Method (posible bar chart)


df3 <- dataframe %>%
  group_by(AB_type) %>%
  summarise(counts = n())

df3 <- df3 %>%
  arrange(desc(AB_type)) %>%
  mutate(prop = round(counts*100/sum(counts), 1),
         lab.ypos = cumsum(prop) - 0.5*prop)







df5 <- dataframe %>%
  group_by(Method) %>%
  summarise(counts = n())

df5 <- df5 %>%
  arrange(desc(Method)) %>%
  mutate(prop = round(counts*100/sum(counts), 1),
         lab.ypos = cumsum(prop) - 0.5*prop)


e<-ggplot(df5, aes(x = Method, y = counts)) +
  labs(title="Method")+
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = counts), vjust = -0.3) + 
  theme_classic()+
  theme(plot.title = element_text(hjust=0.5,size =18),axis.text=element_text(size=7))

print(e)



e <- ggplot(df5, aes(x = "", y = prop, fill = Method)) +
  labs(fill="Método experimental: ") +
  geom_bar(width = 1, stat = "identity", color = "black") +
  geom_label_repel(data = df5,
                   aes(y = lab.ypos, label = counts),
                   size = 4.5, nudge_x = 1, show.legend = FALSE) +  coord_polar("y", start = 0)+  coord_polar("y", start = 0)+
  ggpubr::fill_palette("gsea")+
  theme_void()+
  theme(legend.title = element_text(size = 15),legend.position="top")
print(e)















############# Parte CDRs ##########################
H_pdb=vector()
H1_len=vector()
H2_len=vector()
H3_len=vector()
H1_pdb=vector()
H2_pdb=vector()
H3_pdb=vector()
H1_seq=vector()
H2_seq=vector()
H3_seq=vector()

L_pdb=vector()
L1_len=vector()
L2_len=vector()
L3_len=vector()
L1_pdb=vector()
L2_pdb=vector()
L3_pdb=vector()
L1_seq=vector()
L2_seq=vector()
L3_seq=vector()

for (i in 1:length(data)){
 
   #For H loops  
  if(length(data[[i]]$`Chains H`)==0){
  }
  else if(length(data[[i]]$`Chains H`)==1 || length(data[[i]]$`Chains H`)==2){

    H_pdb=c(H_pdb,data[[i]]$PDB)
   
     if(length(data[[i]]$`Chains H`[[1]]$`H1 length`)){
      H1_pdb=c(H1_pdb,data[[i]]$PDB)
      H1_len=c(H1_len,data[[i]]$`Chains H`[[1]]$`H1 length`)
      H1_seq=c(H1_seq,data[[i]]$`Chains H`[[1]]$`H1 sequence`)
    }
    
    if(length(data[[i]]$`Chains H`[[1]]$`H2 length`)){
      H2_pdb=c(H2_pdb,data[[i]]$PDB)
      H2_len=c(H2_len,data[[i]]$`Chains H`[[1]]$`H2 length`)
      H2_seq=c(H2_seq,data[[i]]$`Chains H`[[1]]$`H2 sequence`)
    }
    
    if(length(data[[i]]$`Chains H`[[1]]$`H3 length`)){
      H3_pdb=c(H3_pdb,data[[i]]$PDB)
      H3_len=c(H3_len,data[[i]]$`Chains H`[[1]]$`H3 length`)
      H3_seq=c(H3_seq,data[[i]]$`Chains H`[[1]]$`H3 sequence`)
    }
  }

  else {
    len1=vector()
    seq1=vector()
    len2=vector()
    seq2=vector()
    len3=vector()   
    seq3=vector()

    for (j in 1:length(data[[i]]$`Chains H`)){
      len1=c(len1,data[[i]]$`Chains H`[[j]]$`H1 length`)
      seq1=c(seq1,data[[i]]$`Chains H`[[j]]$`H1 sequence`)
      
      len2=c(len2,data[[i]]$`Chains H`[[j]]$`H2 length`)
      seq2=c(seq2,data[[i]]$`Chains H`[[j]]$`H2 sequence`)
      
      len3=c(len3,data[[i]]$`Chains H`[[j]]$`H3 length`)
      seq3=c(seq3,data[[i]]$`Chains H`[[j]]$`H3 sequence`)
    }
    if (length(len1)>0){
      H1_pdb=c(H1_pdb,data[[i]]$PDB)
      H1_len=c(H1_len,len1[1])
      H1_seq=c(H1_seq,seq1[1])
    }
    if (length(len2)>0){
      H2_pdb=c(H2_pdb,data[[i]]$PDB)
      H2_len=c(H2_len,len2[1])
      H2_seq=c(H2_seq,seq2[1])
    }
    if (length(len3)>0){
      H3_pdb=c(H3_pdb,data[[i]]$PDB)
      H3_len=c(H3_len,len3[1])
      H3_seq=c(H3_seq,seq3[1])
    }
  }
 
  
  #For L loops  
  if(length(data[[i]]$`Chains L`)==0){
  }
  else if(length(data[[i]]$`Chains L`)==1 || length(data[[i]]$`Chains L`)==2){
    
    L_pdb=c(L_pdb,data[[i]]$PDB)
    
    if(length(data[[i]]$`Chains L`[[1]]$`L1 length`)){
      L1_pdb=c(L1_pdb,data[[i]]$PDB)
      L1_len=c(L1_len,data[[i]]$`Chains L`[[1]]$`L1 length`)
      L1_seq=c(L1_seq,data[[i]]$`Chains L`[[1]]$`L1 sequence`)
    }
    
    if(length(data[[i]]$`Chains L`[[1]]$`L2 length`)){
      L2_pdb=c(L2_pdb,data[[i]]$PDB)
      L2_len=c(L2_len,data[[i]]$`Chains L`[[1]]$`L2 length`)
      L2_seq=c(L2_seq,data[[i]]$`Chains L`[[1]]$`L2 sequence`)
    }
    
    if(length(data[[i]]$`Chains L`[[1]]$`L3 length`)){
      L3_pdb=c(L3_pdb,data[[i]]$PDB)
      L3_len=c(L3_len,data[[i]]$`Chains L`[[1]]$`L3 length`)
      L3_seq=c(L3_seq,data[[i]]$`Chains L`[[1]]$`L3 sequence`)
    }
  }
  
  else {
    len1=vector()
    seq1=vector()
    len2=vector()
    seq2=vector()
    len3=vector()   
    seq3=vector()
    
    for (j in 1:length(data[[i]]$`Chains L`)){
      len1=c(len1,data[[i]]$`Chains L`[[j]]$`L1 length`)
      seq1=c(seq1,data[[i]]$`Chains L`[[j]]$`L1 sequence`)
      
      len2=c(len2,data[[i]]$`Chains L`[[j]]$`L2 length`)
      seq2=c(seq2,data[[i]]$`Chains L`[[j]]$`L2 sequence`)
      
      len3=c(len3,data[[i]]$`Chains L`[[j]]$`L3 length`)
      seq3=c(seq3,data[[i]]$`Chains L`[[j]]$`L3 sequence`)
    }
    if (length(len1)>0){
      L1_pdb=c(L1_pdb,data[[i]]$PDB)
      L1_len=c(L1_len,len1[1])
      L1_seq=c(L1_seq,seq1[1])
    }
    if (length(len2)>0){
      L2_pdb=c(L2_pdb,data[[i]]$PDB)
      L2_len=c(L2_len,len2[1])
      L2_seq=c(L2_seq,seq2[1])
    }
    if (length(len3)>0){
      L3_pdb=c(L3_pdb,data[[i]]$PDB)
      L3_len=c(L3_len,len3[1])
      L3_seq=c(L3_seq,seq3[1])
    }
  }
}

dfH1 <- tibble(H1_pdb,H1_len,H1_seq)
dfH2 <- tibble(H2_pdb,H2_len,H2_seq)
dfH3 <- tibble(H3_pdb,H3_len,H3_seq)

dfL1 <- tibble(L1_pdb,L1_len,L1_seq)
dfL2 <- tibble(L2_pdb,L2_len,L2_seq)
dfL3 <- tibble(L3_pdb,L3_len,L3_seq)


dfapa <- data.frame(CDR = c("Total", "L1", "L2","L3", "H1", "H2","H3"),
                 Counts = c(length(pdbs),length(L1_pdb),length(L2_pdb),length(L3_pdb),length(H1_pdb),length(H2_pdb),length(H3_pdb))
)



  # bar chart CDR
t<-ggplot(dfapa, aes(x = CDR, y = Counts)) +
  labs(title="Apariciones de cada loop CDR")+
  xlab("Loop CDR")+ ylab("Apariciones")+
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = Counts), vjust = -0.3) + 
  theme_classic()+
  theme(plot.title = element_text(hjust=0.5,size =18))

print(t)

  #Density charts

z <- ggplot(dfH1, aes(x = H1_len)) +
  ggtitle("Tamaño H1")+
  xlab("Longitud loop (aminoacidos)")+ ylab("Densidad")+
  geom_density(fill = "#FC4E07", alpha=0.4)+
  xlim(c(1, 30)) +
  geom_vline(aes(xintercept = mean(H1_len)), linetype = "dashed",  size = 0.6, color = "#3C0B15")+
  geom_text(aes(x=mean(H1_len)+2, label=paste0("Media:\n",round(mean(H1_len),2)), y=1.41))+
  theme_pubclean()+ 
  theme(plot.title = element_text(hjust=0.5,size =18))

print(z)

y <- ggplot(dfH2, aes(x = H2_len)) +
  labs(title="Tamaño H2")+
  xlab("Longitud loop (aminoacidos)")+ ylab("Densidad")+
  geom_density(fill = "#FC4E07", alpha=0.4)+
  xlim(c(1, 30)) +
  geom_vline(aes(xintercept = mean(H2_len)), linetype = "dashed",  size = 0.6, color = "#3C0B15")+
  geom_text(aes(x=mean(H2_len)+2, label=paste0("Media:\n",round(mean(H2_len),2)), y=1.41))+
  theme_pubclean()+ 
  theme(plot.title = element_text(hjust=0.5,size =18))

print(y)

x <- ggplot(dfH3, aes(x = H3_len)) +
  labs(title="Tamaño H3")+
  xlab("Longitud loop (aminoacidos)")+ ylab("Densidad")+
  geom_density(fill = "#FC4E07", alpha=0.4)+
  xlim(c(1, 30)) +
  geom_vline(aes(xintercept = mean(H3_len)), linetype = "dashed",  size = 0.6, color = "#3C0B15")+
  geom_text(aes(x=mean(H3_len)+2, label=paste0("Media:\n",round(mean(H3_len),2)), y=0.1))+
  theme_pubclean()+ 
  theme(plot.title = element_text(hjust=0.5,size =18))

print(x)

w <- ggplot(dfL1, aes(x = L1_len)) +
  labs(title="Tamaño L1")+
  xlab("Longitud loop (aminoacidos)")+ ylab("Densidad")+
  geom_density(fill = "#FC4E07", alpha=0.4)+
  xlim(c(1, 30)) +
  geom_vline(aes(xintercept = mean(L1_len)), linetype = "dashed",  size = 0.6, color = "#3C0B15")+
  geom_text(aes(x=mean(L1_len)+2, label=paste0("Media:\n",round(mean(L1_len),2)), y=0.41))+
  theme_pubclean()+ 
  theme(plot.title = element_text(hjust=0.5,size =18))

print(w)

v <- ggplot(dfL2, aes(x = L2_len)) +
  labs(title="Tamaño L2")+
  xlab("Longitud loop (aminoacidos)")+ ylab("Densidad")+
  geom_density(fill = "#FC4E07", alpha=0.4)+
  xlim(c(1, 30)) +
  geom_vline(aes(xintercept = mean(L2_len)), linetype = "dashed",  size = 0.6, color = "#3C0B15")+
  geom_text(aes(x=mean(L2_len)+2,  label=paste0("Media:\n",round(mean(L2_len),2)), y=2.41))+
  theme_pubclean()+ 
  theme(plot.title = element_text(hjust=0.5,size =18))

print(v)

u <- ggplot(dfL3, aes(x = L3_len)) +
  labs(title="Tamaño L3")+
  xlab("Longitud loop (aminoacidos)")+ ylab("Densidad")+
  geom_density(fill = "#FC4E07", alpha=0.4)+
  xlim(c(1, 30)) +
  geom_vline(aes(xintercept = mean(L3_len)), linetype = "dashed",  size = 0.6, color = "#3C0B15")+
  geom_text(aes(x=mean(L3_len)+2,  label=paste0("Media:\n",round(mean(L3_len),2)), y=0.61))+
  theme_pubclean()+ 
  theme(plot.title = element_text(hjust=0.5,size =18))

print(u)



#### Print the entire multiplot #########

tt<-list(a,b,c,d,e,t,z,y,x,w,v,u)

pp<-matrix(c(1,2,3,4,5,6,7,8,9,10,11,12), nrow=4, byrow=TRUE)

multiplot(plotlist=tt, layout=pp)



first <- list(sp, a,b,c,e,t)
mat<-matrix(c(1,2,3,4,5,6), nrow=2, byrow=TRUE)

multiplot(plotlist=first, layout=mat)


densi <- list(z,y,x,w,v,u)

mat<-matrix(c(1,4,2,5,3,6), nrow=3, byrow=TRUE)
multiplot(plotlist=densi, layout=mat)


